//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:36:05 PM EST 
//

package com.lndb.dwtool.erm.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ColumnLayout complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ColumnLayout">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columnLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columnSearchable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="columnEditable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnLayout", propOrder = { "columnName", "columnLabel", "columnSearchable", "columnEditable" })
public class ColumnLayout {

    @XmlElement(required = true)
    protected String columnName;
    @XmlElement(required = true)
    protected String columnLabel;
    protected boolean columnSearchable;
    protected boolean columnEditable;

    /**
     * Gets the value of the columnName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getColumnName() {
	return columnName;
    }

    /**
     * Sets the value of the columnName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setColumnName(String value) {
	this.columnName = value;
    }

    /**
     * Gets the value of the columnLabel property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getColumnLabel() {
	return columnLabel;
    }

    /**
     * Sets the value of the columnLabel property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setColumnLabel(String value) {
	this.columnLabel = value;
    }

    /**
     * Gets the value of the columnSearchable property.
     * 
     */
    public boolean isColumnSearchable() {
	return columnSearchable;
    }

    /**
     * Sets the value of the columnSearchable property.
     * 
     */
    public void setColumnSearchable(boolean value) {
	this.columnSearchable = value;
    }

    /**
     * Gets the value of the columnEditable property.
     * 
     */
    public boolean isColumnEditable() {
	return columnEditable;
    }

    /**
     * Sets the value of the columnEditable property.
     * 
     */
    public void setColumnEditable(boolean value) {
	this.columnEditable = value;
    }

}
