//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:36:05 PM EST 
//

package com.lndb.dwtool.erm.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.lndb.dwtool.erm.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.lndb.dwtool.erm.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TableLayout }
     * 
     */
    public TableLayout createTableLayout() {
	return new TableLayout();
    }

    /**
     * Create an instance of {@link ColumnLayout }
     * 
     */
    public ColumnLayout createColumnLayout() {
	return new ColumnLayout();
    }

    /**
     * Create an instance of {@link TableLayout.Columns }
     * 
     */
    public TableLayout.Columns createTableLayoutColumns() {
	return new TableLayout.Columns();
    }

}
