//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:36:05 PM EST 
//

package com.lndb.dwtool.erm.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tableName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tableLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tableEditable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="tableDeletable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="columns">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ColumnLayout" type="{}ColumnLayout" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "tableName", "tableLabel", "tableEditable", "tableDeletable", "columns" })
@XmlRootElement(name = "TableLayout")
public class TableLayout {

    @XmlElement(required = true)
    protected String tableName;
    @XmlElement(required = true)
    protected String tableLabel;
    protected boolean tableEditable;
    protected boolean tableDeletable;
    @XmlElement(required = true)
    protected TableLayout.Columns columns;

    /**
     * Gets the value of the tableName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTableName() {
	return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTableName(String value) {
	this.tableName = value;
    }

    /**
     * Gets the value of the tableLabel property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTableLabel() {
	return tableLabel;
    }

    /**
     * Sets the value of the tableLabel property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTableLabel(String value) {
	this.tableLabel = value;
    }

    /**
     * Gets the value of the tableEditable property.
     * 
     */
    public boolean isTableEditable() {
	return tableEditable;
    }

    /**
     * Sets the value of the tableEditable property.
     * 
     */
    public void setTableEditable(boolean value) {
	this.tableEditable = value;
    }

    /**
     * Gets the value of the tableDeletable property.
     * 
     */
    public boolean isTableDeletable() {
	return tableDeletable;
    }

    /**
     * Sets the value of the tableDeletable property.
     * 
     */
    public void setTableDeletable(boolean value) {
	this.tableDeletable = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * @return possible object is {@link TableLayout.Columns }
     * 
     */
    public TableLayout.Columns getColumns() {
	return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *            allowed object is {@link TableLayout.Columns }
     * 
     */
    public void setColumns(TableLayout.Columns value) {
	this.columns = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ColumnLayout" type="{}ColumnLayout" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "columnLayout" })
    public static class Columns {

	@XmlElement(name = "ColumnLayout", required = true)
	protected List<ColumnLayout> columnLayout;

	/**
	 * Gets the value of the columnLayout property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the columnLayout property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getColumnLayout().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ColumnLayout }
	 * 
	 * 
	 */
	public List<ColumnLayout> getColumnLayout() {
	    if (columnLayout == null) {
		columnLayout = new ArrayList<ColumnLayout>();
	    }
	    return this.columnLayout;
	}

    }

}
